import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useExploreProfilesQuery } from "../generated/graphql";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data, loading, error } = useExploreProfilesQuery({});
  const profiles = data?.exploreProfiles.items;

  if (loading) return <div>Loading</div>;
  if (error) return <div>Error</div>;
  return (
    <>
      <Head>
        <title>C-lens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {profiles?.map((profile) => (
          <div key={profile.id}>{profile.name}</div>
        ))}
      </main>
    </>
  );
}
